add complications routers
movie-recommendations/backend pull request #13
Opened 2023-07-10 15:15 UTC by Rayder7

Добавил вывод по id подборок;
добавил отображение подборок от редакции и избранные

2023-07-10 19:07 UTC, Rabadan-Ibr requested changes

2023-07-10 19:07 UTC, Rabadan-Ibr commented on morec/api/serializers/compilations.py
> +                  'from_redaction')
from_redaction отображать не нужно, это поле для внутреннего использования, чтоб фильтровать подборки.
В данный момент один сериализатор для отображения подборки, и в списке и отдельно. Думаю лучше разбить на отдельные. один более подробный для отдельного, другой для отображения в списке. 
Плюс фильмы в подборке, их нужно чуть подробнее.

2023-07-11 05:04 UTC, Rayder7 commented on morec/api/views/compilations.py
> +class CompliationSoloViewSet(generics.RetrieveAPIView):
> почему бы не объединить в один вьюсет тот что на 8 и 14 строках?

Слушай, тот что на 14 он query берет список от редакции. А в 8 строке он даёт любую подборку взять. Я поэтому и разделил

2023-07-11 09:03 UTC, Rabadan-Ibr commented on morec/api/views/compilations.py
> +class CompliationSoloViewSet(generics.RetrieveAPIView):
Да, точно. Забыл про фильтр.

2023-07-11 14:32 UTC, Rabadan-Ibr requested changes

2023-07-11 14:32 UTC, Rabadan-Ibr commented on morec/api/views/compilations.py
>  class ComplilationFavoriteListViewSet(viewsets.ModelViewSet):
Не заметил в первом коммите. а почему здесь и выше используется ModelViewSet? На данном этапе они должны отдавать только список. А сейчас будут роуты на полный набор. Можно использовать пару лист модел микшин и генерик. Ну и гет сериализер класс будет пока не нужен.

2023-07-11 14:32 UTC, Rabadan-Ibr commented on morec/api/serializers/compilations.py
> +        fields = ('id', 'title', 'movies')
фильмы пока ещё выводятся не так как хотелось бы. Можно создать для них отдельный сериализатор с нужными полями, и указать его для movies

2023-07-11 15:44 UTC, Rabadan-Ibr requested changes

2023-07-11 20:03 UTC, Rabadan-Ibr commented on morec/api/serializers/compilations.py
> +            'genres',
на макете ещё год есть. его то же можно добавить. А жанры в списковом варианте не обязательно так подробно, там текстового представления хватает. Но это можно потом переделать, все равно пока макет утвердят ещё что то найдется.

2023-07-11 20:03 UTC, Rabadan-Ibr commented on morec/api/views/compilations.py
>          User = self.request.user
Переменные с маленькой буквы. Путает а то, типа класс.

2023-07-12 20:25 UTC, Rabadan-Ibr approved these changes

2023-07-13 07:45 UTC, Toksi86 approved these changes

2023-07-13 13:10 UTC, merged