Create users models
movie-recommendations/backend pull request #9
Opened 2023-07-05 17:52 UTC by AlexMinVrn

2023-07-06 18:01 UTC, Rabadan-Ibr requested changes

2023-07-06 18:01 UTC, Rabadan-Ibr commented on morec/users/managers.py
> +        user.is_admin = True
У модели юзер сейчас нет поля is_admin. 
Либо тут можно поменять на is_staff? либо у модели на is_admin.

2023-07-06 18:09 UTC, AlexMinVrn commented on morec/users/managers.py
> +        user.is_admin = True
Исправил в managers.py

2023-07-06 19:05 UTC, Rabadan-Ibr commented on morec/users/models.py
> +    username = models.SlugField(
У нас это поле не совсем slug, как мне кажется тут достаточно обычного CharField. Slug не содержит в себе символов которые нельзя писать в path параметре (в url строке). А без уникальности мы его точно там использовать не будем.

2023-07-06 19:05 UTC, Rabadan-Ibr commented on morec/users/models.py
> +class User(AbstractBaseUser):
предложил бы использовать uuid для пользователя в качестве PK. В случае чего можем потом и в патч параметре использовать.

2023-07-06 19:30 UTC, AlexMinVrn commented on morec/users/models.py
> +class User(AbstractBaseUser):
id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

2023-07-06 19:51 UTC, AlexMinVrn commented on morec/users/models.py
> +class User(AbstractBaseUser):
Добавил поле ID

2023-07-06 21:56 UTC, Rabadan-Ibr approved these changes

2023-07-07 04:25 UTC, Rayder7 approved these changes

2023-07-07 07:20 UTC, merged